apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-auth
  namespace: openfaas
  labels:
    app: edge-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-auth
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      labels:
        app: edge-auth
    spec:
      containers:
      - name: edge-auth
        image: ghcr.io/openfaas/ofc-edge-auth:0.14.6
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 2
        env:
          - name: port
            value: "8080"
          - name: write_debug
            value: "false"
        ports:
        - containerPort: 8080
          protocol: TCP
