environment:
  validate_hmac: "1"
# URLs
  gateway_url:  http://gateway.openfaas:8080/
  gateway_public_url: {{.Scheme}}://cloud.{{.RootDomain}}/
  # Add your custom templates by adding a coma separated URL, i.e. extend the current value with:
  # ", https://github.com/custom/template.git, https://github.com/custom/template2.git"
  custom_templates: {{ .CustomTemplates }}

# Security
  basic_auth: true
  secret_mount_path: /var/openfaas/secrets

# Function policy
  readonly_root_filesystem: true
  scaling_min_limit: 1
  scaling_max_limit: 4
  prometheus_host: prometheus.openfaas
  prometheus_port: 9090
  metrics_window: 60m
