provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  billing:
    lang: golang-middleware
    handler: ./billing
    # image: ghcr.io/${REPO:-codius}/ofc-billing:latest
    image: ghcr.io/${REPO:-codius}/ofc-billing:dev
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - gateway_config.yml
    environment:
      cost_per_unit_invocations: ${cost_per_unit_invocations:-10}
      unit_invocations: ${unit_invocations:-1000}
      bonus_invocations: ${bonus_invocations:-50}
      balances_key_prefix: "balances"
      write_debug: true
      combine_output: false
    secrets:
      - redis-password

  garbage-collect:
    lang: go
    handler: ./garbage-collect
    image: ghcr.io/${REPO:-openfaas}/ofc-garbage-collect:0.14.6
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      read_timeout: 30s
      write_timeout: 30s
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret

  list-functions:
    lang: go
    handler: ./list-functions
    image: ghcr.io/${REPO:-openfaas}/ofc-list-functions:0.14.6
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password

  metrics:
    lang: go
    handler: ./metrics
    image: ghcr.io/${REPO:-openfaas}/ofc-system-metrics:0.14.6
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - gateway_config.yml
    environment:
      content_type: "application/json"

  function-logs:
    lang: go
    handler: ./function-logs
    image: ghcr.io/${REPO:-openfaas}/ofc-function-logs:0.14.6
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password

