provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  garbage-collect:
    lang: go
    handler: ./garbage-collect
    image: ghcr.io/${REPO:-openfaas}/ofc-garbage-collect:0.14.6
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      read_timeout: 30s
      write_timeout: 30s
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret

  import-secrets:
    lang: go
    handler: ./import-secrets
    image: ghcr.io/${REPO:-openfaas}/ofc-import-secrets:0.14.6
    annotations:
      com.openfaas.serviceaccount: sealedsecrets-importer-rw
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      validate_hmac: true
      combined_output: false
    environment_file:
      - github.yml
    secrets:
      - payload-secret

  list-functions:
    lang: go
    handler: ./list-functions
    image: ghcr.io/${REPO:-openfaas}/ofc-list-functions:0.14.6
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password

  metrics:
    lang: go
    handler: ./metrics
    image: ghcr.io/${REPO:-openfaas}/ofc-system-metrics:0.14.6
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - gateway_config.yml
    environment:
      content_type: "application/json"

  function-logs:
    lang: go
    handler: ./function-logs
    image: ghcr.io/${REPO:-openfaas}/ofc-function-logs:0.14.6
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password

